services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev
    hostname: dev
    ports:
      - "12345:12345"
    volumes:
      - /volume2/homes/wilson/Work:/Work
    network_mode: bridge
